remote_theme: "mmistakes/so-simple-theme"
logo: "/images/icon.png"
locale: "en-us"
title: "SONORA"
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
